### ISSUE TITLE
showfish does not show all about fish

### ISSUE THREAD

**Issue by ThaCheeseBun** [ReeZey/risig#1]
hello my dear friend. the showfish command does not show all information available about the fish, and this is big problem. if i want to know price of fish after i caught i need to search in channel and that is not convient. please add all fish info to the showfish command. many thanks!
[Screenshot_20230716-195132_1.png](https://github.com/ReeZey/risig/assets/36112086/6e80050d-a85c-4c30-9cb8-6b22d4ef5dd3)

**Comment by ReeZey** [comment]
hello this is fixed now please have a good day and enjoy your more fishing trips with some more information of how much fish weight, length, AND PRICE!!!!!!! 😃😃😃😃😃😃😃😃😃 bye bye have nice good life!
